---
- name: Install nano
  yum: name=nano state=present

- name: Install git
  yum: name=git state=present

- name: Download nanorc from Github
  git: repo=https://github.com/nanorc/nanorc dest=~/nanorc

- name: Install nanorc globally
  command: make install-global
  args:
    chdir: ~/nanorc
    creates: /usr/local/share/nano/

- name: Create .nanorc file
  copy: src=nanorc dest={{ nanorc_rc_file_path }}
